blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/blackoutsecure/.github/security/policy
    about: Please report security vulnerabilities here.
  - name: General support
    url: https://blackoutsecure.app
    about: For general questions and support.
